server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=stickynotes;encrypt=false
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false